### ISSUE TITLE
can't move file 

### ISSUE THREAD

**Issue by LorenzoTa** [MartinMcGrath/ms-ebook-dl#1]
I got this error:
`Can't move file "C:\Users\ -- user string --\AppData\Local\Temp\mojo.tmp.WR2TZu6aBjLY2UYs" to "Office/Azure AD/Office 365 seamless sign-in.PDF": No such file or directory at D:/ulisseDUE/perl5.26.64bit/perl/vendor/lib/Mojo/Asset/File.pm line 106.`

I suppose because `Azure AD/Office 365 seamless sign-in` contains a forward slash

**Comment by MartinMcGrath** [comment]
Hi, thanks for reporting this issue. I've implemented a quick fix in https://github.com/MartinMcGrath/ms-ebook-dl/commit/6ea389b4407dc2006ecb0f232072f433b395fb93

**Comment by MartinMcGrath** [comment]
Closed, an improved fix from @choroba in https://github.com/MartinMcGrath/ms-ebook-dl/commit/eae65c375ee8c881894c50c041b86facc3aa5ca4
